rust: id_pool: fix broken intra-doc link
`rustdoc` detects a broken intra-doc link:

    error: unresolved link to `BitmapVec::NO_ALLOC_MAX_LEN`
       --> rust/kernel/id_pool.rs:100:31
        |
    100 |     /// [`NO_ALLOC_MAX_LEN`]: BitmapVec::NO_ALLOC_MAX_LEN
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the struct `BitmapVec` has no field or associated item named `NO_ALLOC_MAX_LEN`
        |
        = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

Thus fix it.

It was a missed rename in v5 of the patch series adding this [1].

Fixes: feb3fdf1239a ("rust: id_pool: do not supply starting capacity")
Link: https://lore.kernel.org/all/20251112-binder-bitmap-v5-0-8b9d7c7eca82@google.com/ [1]
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
Signed-off-by: Yury Norov (NVIDIA) <yury.norov@gmail.com>