orangefs: move s_kmod_keyword_mask_map[] into debugfs.c
gcc warns about unused const variables when building with W=1

    In file included from fs/orangefs/protocol.h:287,
                     from fs/orangefs/acl.c:8:
    fs/orangefs/orangefs-debug.h:86:18: error: 'num_kmod_keyword_mask_map' defined but not used [-Werror=unused-const-variable=]
       86 | static const int num_kmod_keyword_mask_map = (int)
          |                  ^~~~~~~~~~~~~~~~~~~~~~~~~

This one is only used in one file, so just move the definition
next to its only user.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mike Marshall <hubcap@omnibond.com>