PCI: altera: Use dev_fwnode() for irq_domain_create_linear()
irq_domain_create_simple() takes fwnode as the first argument. It can be
extracted from the struct device using dev_fwnode() helper instead of
using of_node with of_fwnode_handle().

So use the dev_fwnode() helper.

This also removes an unused 'node' variable that is only used when
CONFIG_OF is enabled:

  drivers/pci/controller/pcie-altera.c: In function 'altera_pcie_init_irq_domain':
  drivers/pci/controller/pcie-altera.c:855:29: error: unused variable 'node' [-Werror=unused-variable]
    855 |         struct device_node *node = dev->of_node;

Fixes: 4b5e1d97154d ("PCI: Switch to irq_domain_create_linear()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
[mani: fixed the commit SHA]
Signed-off-by: Manivannan Sadhasivam <mani@kernel.org>
[bhelgaas: align subject/commit log with Jiri's similar patches]
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
Reviewed-by: Jiri Slaby <jirislaby@kernel.org>
Link: https://patch.msgid.link/20250521163329.2137973-1-arnd@kernel.org